// Test stub for the `virtual:pwa-register/react` module generated by vite-plugin-pwa
export const useRegisterSW = () => ({
  needRefresh: [false, () => {}] as const,
  offlineReady: [false, () => {}] as const,
  updateServiceWorker: async () => {},
});
