import type { RecurrenceRule } from '@/lib/recurrence';
import { COMMON_ERROR_MESSAGES, type CommonError } from '@/shared/constants';
import type { Result } from '@/shared/types';

// Re-export DB types
export type {
  Expense,
  ExpenseParticipant,
  NewExpense,
  NewExpenseParticipant,
} from '@/db/schema';
export type { RecurrenceRule } from '@/lib/recurrence';

// Form data types
export interface CreateExpenseFormData {
  readonly amount: number; // in cents
  readonly description: string;
  readonly date: string; // YYYY-MM-DD
  readonly paidBy: string; // memberId
  readonly participants: ReadonlyArray<{
    readonly memberId: string;
    readonly customAmount: number | null;
  }>;
}

export interface UpdateExpenseFormData {
  readonly amount?: number | undefined;
  readonly description?: string | undefined;
  readonly date?: string | undefined;
  readonly paidBy?: string | undefined;
  readonly participants?:
    | ReadonlyArray<{
        readonly memberId: string;
        readonly customAmount: number | null;
      }>
    | undefined;
}

// API response types
export interface ExpenseSummary {
  readonly id: string;
  readonly groupId: string;
  readonly paidBy: {
    readonly id: string;
    readonly name: string;
    readonly isJointAccount: boolean;
  };
  readonly amount: number; // cents
  readonly description: string;
  readonly date: string; // YYYY-MM-DD
  readonly createdBy: {
    readonly id: string;
    readonly name: string;
  };
  readonly createdAt: string; // ISO date
  readonly participantCount: number;
  readonly myShare: number | null; // cents, null if not a participant
  readonly recurringExpenseId: string | null; // set when generated by a recurrence
}

export interface ParticipantDetail {
  readonly id: string;
  readonly memberId: string;
  readonly memberName: string;
  readonly customAmount: number | null;
  readonly calculatedShare: number; // cents
  readonly isCurrentUser: boolean;
}

export interface ExpenseDetail {
  readonly id: string;
  readonly groupId: string;
  readonly paidBy: {
    readonly id: string;
    readonly name: string;
    readonly isCurrentUser: boolean;
    readonly isJointAccount: boolean;
  };
  readonly amount: number;
  readonly description: string;
  readonly date: string;
  readonly createdBy: {
    readonly id: string;
    readonly name: string;
    readonly isCurrentUser: boolean;
  };
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly participants: ReadonlyArray<ParticipantDetail>;
  // Recurrence that generated this expense (kept, with isDeleted, after its deletion)
  readonly recurrence: {
    readonly id: string;
    readonly rule: RecurrenceRule;
    readonly isDeleted: boolean;
  } | null;
}

// Filter types
export interface ExpenseFilters {
  readonly startDate?: string | undefined;
  readonly endDate?: string | undefined;
  readonly paidBy?: string | undefined;
  readonly participantId?: string | undefined;
  readonly search?: string | undefined;
  readonly recurring?: boolean | undefined; // only expenses generated by a recurrence
}

// Recurring expenses (contract: specs/003-recurring-expenses/contracts)
export type RecurrenceStatus = 'active' | 'paused' | 'disabled';
export type PausedReason = 'payer_inactive' | 'no_active_participant';

export interface RecurringExpenseSummary {
  readonly id: string;
  readonly description: string;
  readonly amount: number; // cents
  readonly rule: RecurrenceRule;
  readonly startDate: string; // YYYY-MM-DD
  readonly nextDueDate: string | null; // null unless active
  readonly status: RecurrenceStatus;
  readonly pausedReason: PausedReason | null;
  readonly paidBy: {
    readonly id: string;
    readonly name: string;
    readonly isJointAccount: boolean;
    readonly isActive: boolean;
  };
}

export interface RecurringExpenseParticipantDetail {
  readonly memberId: string;
  readonly memberName: string;
  readonly customAmount: number | null;
  readonly calculatedShare: number; // cents, what an expense generated now would split into
  readonly isActive: boolean;
  readonly isCurrentUser: boolean;
}

export interface RecurringExpenseDetail extends RecurringExpenseSummary {
  readonly createdBy: {
    readonly id: string;
    readonly name: string;
    readonly isCurrentUser: boolean;
  };
  readonly participants: ReadonlyArray<RecurringExpenseParticipantDetail>;
}

export interface CreateRecurringExpenseData {
  readonly amount: number; // cents
  readonly description: string;
  readonly paidBy: string;
  readonly participants: ReadonlyArray<{
    readonly memberId: string;
    readonly customAmount: number | null;
  }>;
  readonly startDate: string; // YYYY-MM-DD
  readonly rule: RecurrenceRule;
}

export interface UpdateRecurringExpenseData {
  readonly amount?: number | undefined;
  readonly description?: string | undefined;
  readonly paidBy?: string | undefined;
  readonly participants?: CreateRecurringExpenseData['participants'] | undefined;
  readonly rule?: RecurrenceRule | undefined;
}

export interface CreateRecurringExpenseResult {
  readonly id: string;
  readonly nextDueDate: string;
  readonly generatedExpenseId: string | null;
}

export interface ReactivateRecurringExpenseResult {
  readonly success: true;
  readonly nextDueDate: string;
  readonly generatedExpenseId: string | null;
}

// Pagination types
export interface ExpensesPage {
  readonly expenses: ReadonlyArray<ExpenseSummary>;
  readonly nextCursor: string | null;
  readonly hasMore: boolean;
}

// Error types
export type ExpenseError =
  | CommonError
  | 'EXPENSE_NOT_FOUND'
  | 'INVALID_AMOUNT'
  | 'INVALID_DESCRIPTION'
  | 'INVALID_DATE'
  | 'INVALID_PAYER'
  | 'NO_PARTICIPANTS'
  | 'INVALID_PARTICIPANT'
  | 'CUSTOM_AMOUNTS_EXCEED_TOTAL'
  | 'RECURRING_EXPENSE_NOT_FOUND'
  | 'START_DATE_IN_PAST'
  | 'INVALID_RULE';

export const EXPENSE_ERROR_MESSAGES = {
  ...COMMON_ERROR_MESSAGES,
  EXPENSE_NOT_FOUND: 'Dépense introuvable',
  INVALID_AMOUNT: 'Le montant doit être positif',
  INVALID_DESCRIPTION: 'La description est requise',
  INVALID_DATE: 'La date est invalide',
  INVALID_PAYER: 'Le payeur est invalide',
  NO_PARTICIPANTS: 'Au moins un participant est requis',
  INVALID_PARTICIPANT: 'Un participant est invalide',
  CUSTOM_AMOUNTS_EXCEED_TOTAL: 'Les montants personnalisés dépassent le total',
  RECURRING_EXPENSE_NOT_FOUND: 'Récurrence introuvable',
  START_DATE_IN_PAST:
    "La répétition commence au plus tôt aujourd'hui. Saisissez les dépenses passées une par une.",
  INVALID_RULE: 'La fréquence est invalide',
} as const satisfies Record<ExpenseError, string>;

// Valid error values for type narrowing with toTypedError
export const VALID_EXPENSE_ERRORS: readonly ExpenseError[] = [
  'UNKNOWN_ERROR',
  'NOT_A_MEMBER',
  'EXPENSE_NOT_FOUND',
  'INVALID_AMOUNT',
  'INVALID_DESCRIPTION',
  'INVALID_DATE',
  'INVALID_PAYER',
  'NO_PARTICIPANTS',
  'INVALID_PARTICIPANT',
  'CUSTOM_AMOUNTS_EXCEED_TOTAL',
  'RECURRING_EXPENSE_NOT_FOUND',
  'START_DATE_IN_PAST',
  'INVALID_RULE',
] as const;

// API result type alias
export type ExpenseResult<T = void> = Result<T, ExpenseError>;
