import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import type { ExpenseSummary } from '../types';
import { ExpenseCard } from './ExpenseCard';

const expense = (overrides: Partial<ExpenseSummary> = {}): ExpenseSummary => ({
  id: 'e1',
  groupId: 'g1',
  paidBy: { id: 'alex', name: 'Alex', isJointAccount: false },
  amount: 85000,
  description: 'Loyer',
  date: '2026-10-01',
  createdBy: { id: 'alex', name: 'Alex' },
  createdAt: '2026-10-01T00:00:00.000Z',
  participantCount: 2,
  myShare: 42500,
  recurringExpenseId: null,
  ...overrides,
});

describe('ExpenseCard', () => {
  it('marks an expense generated by a recurrence, also for screen readers', () => {
    render(<ExpenseCard expense={expense({ recurringExpenseId: 'r1' })} currency="EUR" />);
    expect(screen.getByRole('button')).toHaveAccessibleName(/Dépense récurrente,/);
    expect(screen.getByRole('button').querySelector('svg[aria-hidden="true"]')).not.toBeNull();
  });

  it('does not mark a manual expense', () => {
    render(<ExpenseCard expense={expense()} currency="EUR" />);
    expect(screen.getByRole('button')).not.toHaveAccessibleName(/Dépense récurrente/);
    expect(screen.getByRole('button').querySelector('svg')).toBeNull();
  });
});
